sudo: false
language: node_js
node_js:
  - 14
  - 13
  - 12
  - 11
  - 10
cache:
  directories:
  - node_modules

env:
  with: out

before_script:
  - (cd test/bundle && npm install --loglevel=error)
