version: 1.0.{build}-{branch}

cache:
  - node_modules

environment:
  matrix:
    - NOV: 14
    - NOV: 13
    - NOV: 12
    - NOV: 11
    - NOV: 10

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NOV $env:PLATFORM
  - npm install
  - cmd /c "cd test/bundle && npm install --loglevel=error"

build: off

before_test:
  - node -v
  - npm -v

test_script:
  - npm test

after_test:
  - npm pack

artifacts:
  - path: "*.tgz"
    name: NPM package
